apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "helmfile-cd.fullname" . }}
  labels:
    {{- include "helmfile-cd.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      {{- with .Values.cronjob.deadline }}
      activeDeadlineSeconds: {{ . }}
      {{- end }}
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "helmfile-cd.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "helmfile-cd.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
          - name: helmfile-cd
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            envFrom:
            - configMapRef:
                name: {{ include "helmfile-cd.fullname" . }}
            volumeMounts:
            - mountPath: /auth
              name: authentication
            - mountPath: /work
              name: work
            - mountPath: /home/helmfile
              name: home
          volumes:
          - name: home
            emptyDir: {}
          - name: authentication
            secret:
              secretName: {{ include "helmfile-cd.gitSecretName" . }}
              defaultMode: 256
              optional: true
          - name: work
            {{- if .Values.persistence.enabled }}
            persistentVolumeClaim:
              claimName: {{ include "helmfile-cd.pvcName" . }}
            {{- else }}
            emptyDir: {}
            {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
