{{- if not .Values.git.authentication.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helmfile-cd.gitSecretName" . }}
  labels:
    {{- include "helmfile-cd.labels" . | nindent 4 }}
  {{- with .Values.git.authentication.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
{{- with .Values.git.authentication.username }}
  username: {{ . | b64enc }}
{{- end }}
{{- with .Values.git.authentication.password }}
  password: {{ . | b64enc }}
{{- end }}
{{- with .Values.git.authentication.key }}
  key: {{ . | b64enc }}
{{- end }}
{{- end }}
